services:
  gateway-service:
    container_name: "gateway-service"
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:4000"
    command: ["node", "/home/client/app/dist/client/app/src/main.js"]
    depends_on:
      - order-service
      - wallet-service
      - authentication-service
      - car-service
      - user-service
      - email-service

  order-service:
    container_name: "order-service-nest"
    build:
      context: .
      dockerfile: ./microservices/order-service/Dockerfile
    env_file:
      - ./microservices/order-service/.env
    ports:
      - "4503:4503"
    command:
      ["node", "/home/order-service/app/dist/order-service/app/src/main.js"]
    depends_on:
      - wallet-service
      - authentication-service
      - car-service
      - user-service
      - email-service
      - db
    networks:
      - nest-microservices

  wallet-service:
    container_name: "wallet-service-nest"
    build:
      context: .
      dockerfile: ./microservices/wallet-service/Dockerfile
    env_file:
      - ./microservices/wallet-service/.env
    ports:
      - "4500:4500"
    command:
      ["node", "/home/wallet-service/app/dist/wallet-service/app/src/main.js"]
    depends_on:
      - authentication-service
      - car-service
      - user-service
      - email-service
      - db
    networks:
      - nest-microservices

  authentication-service:
    container_name: "authentication-service-nest"
    build:
      context: .
      dockerfile: ./microservices/authentication-service/Dockerfile
    env_file:
      - ./microservices/authentication-service/.env
    ports:
      - "5302:5302"
    command:
      [
        "node",
        "/home/authentication-service/app/dist/authentication-service/app/src/main.js",
      ]
    depends_on:
      - car-service
      - user-service
      - email-service
      - db
    networks:
      - nest-microservices

  car-service:
    container_name: "car-service-nest"
    build:
      context: .
      dockerfile: ./microservices/car-service/Dockerfile
    env_file:
      - ./microservices/car-service/.env
    ports:
      - "4507:4507"
    command: ["node", "/home/car-service/app/dist/car-service/app/src/main.js"]
    depends_on:
      - user-service
      - email-service
      - db
    networks:
      - nest-microservices

  user-service:
    container_name: "user-service-nest"
    build:
      context: .
      dockerfile: ./microservices/user-service/Dockerfile
    env_file:
      - ./microservices/user-service/.env
    ports:
      - "4502:4502"
    command:
      ["node", "/home/user-service/app/dist/user-service/app/src/main.js"]
    depends_on:
      - email-service
      - db
    networks:
      - nest-microservices

  email-service:
    container_name: "email-service-nest"
    build:
      context: .
      dockerfile: ./microservices/notification-service/Dockerfile
    env_file:
      - ./microservices/notification-service/.env
    ports:
      - "4504:4504"
    command:
      [
        "node",
        "/home/notification-service/app/dist/notification-service/app/src/main.js",
      ]
    depends_on:
      - redis
    networks:
      - nest-microservices

  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog-server"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - nest-microservices

  db:
    container_name: "mongodb-server-car"
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - nest-microservices

  redis:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6739"
    networks:
      - nest-microservices

networks:
  nest-microservices:
    driver: bridge

volumes:
  mongodb_data_container:
